provider:
  name: openfaas
  gateway: http://127.0.0.1:3000

functions:
  cloudrunopenfaas:
    lang: node12
    handler: ./src
    image: cloudrunopenfaas:latest-1.0
    labels:
      com.openfaas.scale.zero: false